apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww-spark"
  namespace: dognauts-mtp
spec:
  type: Python
  mode: cluster
  image: "registry.neomsa.ru/docker-mlops/mlops/batch-images/batch-model-breast_cancer:2"
  imagePullPolicy: Always
  mainApplicationFile: "local:///model/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww_spark_job.py"
  sparkVersion: 3.1.1
  sparkConf:
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    spark.executor.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 0
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 1
    onSubmissionFailureRetryInterval: 10
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    annotations:
      sidecar.istio.io/inject: 'true'
      vault.security.banzaicloud.io/registry-skip-verify: 'true'
      vault.security.banzaicloud.io/vault-addr: https://vault.vault-infra:8200
      vault.security.banzaicloud.io/vault-env-from-path: secret/data/secret/dognauts/project//dognauts-mtp
      vault.security.banzaicloud.io/vault-role: default
      vault.security.banzaicloud.io/vault-skip-verify: 'true'
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: 1
    labels:
      version: 3.1.1
    annotations:
      sidecar.istio.io/inject: 'true'
      vault.security.banzaicloud.io/registry-skip-verify: 'true'
      vault.security.banzaicloud.io/vault-addr: https://vault.vault-infra:8200
      vault.security.banzaicloud.io/vault-env-from-path: secret/data/secret/dognauts/project//dognauts-mtp
      vault.security.banzaicloud.io/vault-role: default
      vault.security.banzaicloud.io/vault-skip-verify: 'true'